language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bentonwong/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bentonwong/docker-react npm run test
